export CONFIG_ARCH := x86_64
export CONFIG_TARGET := $(CONFIG_ARCH)-pc-linux
export CONFIG_BINUTILS_VERSION := 2.31.1
export CONFIG_GCC_VERSION := 8.2.0
export CONFIG_MPFR_VERSION := 4.0.1
export CONFIG_GMP_VERSION := 6.1.2
export CONFIG_MPC_VERSION := 1.1.0
